### ISSUE TITLE
Error: No module named 'PIL' in Termux

### ISSUE THREAD

**Issue by SalehLardhi** [caronero/Z-ransom#1]
I'm using Termux and have successfully execute the script `install.sh` , but when i wanted to run the program:

~/Z-ransom$ `python3 zransom.py`

It gives me an error is like:

> Traceback (most recent call last):
>   File  "/data/data/com.termux/files/home/Z-ransom/zransom.py", line 4, in <module>
> from PIL import Image
> ModuleNotFoundError: No module named 'PIL'

**Comment by tabi8890** [comment]
Same here anyone helps us
