### ISSUE TITLE
Doesnt Decrypt

### ISSUE THREAD

**Issue by AwakeningHack** [caronero/Z-ransom#3]
When i tested it on bluestacks, it executed beautifully.
Yet when i wanted to unlock/decrypt it just hangs... Cant do anything

**Comment by caronero** [comment]
try it with real phone but be careful

**Comment by Awakeninghacks** [comment]
Thanks for your reply. i have a couple of things i would like to ask you. if you dont mind can we talk on telegram? @Whoopsie8888
Its regarding Whatsapp bots.

**Comment by Awakeninghacks** [comment]
Thanks for your reply. i have a couple of things i would like to ask you. if you dont mind can we talk on telegram? @Whoopsie8888
Its regarding Whatsapp bots.
